### PR TITLE
Nl view order history

### PR DESCRIPTION
**Pull request by Nolan-Little**
## Link to Ticket
Closes # [17](https://github.com/garrulous-gobies/Bangazon-sprint-2/issues/17)

## Description of Proposed Changes

- User profile now has a button to view order history
-links to a list of all past closed orders by Id#, each is a hyperlink
- Hyperlink takes you to a detail page where each product is displayed as a line item with price
-calculated tax and grand total included

## Steps to Test

```
git fetch --all
git checkout nl-view-order-history

python manage.py test
```
Test creating a new cart and ensuring that it doesn't show in order history until completed.

## Impacted Areas in Application

List general components of the application that this PR will affect:

* Profile view
* order history

## Mentions @username

Tag users that need to review this code

### CODE REVIEW

**Comment by amazoradi** [comment]
👍

**Comment by braddavistech** [comment]
👍 Looks good. We may want to add a "$" in front of the dollar figures but it looks great.

**Comment by pragmatic-zac** [comment]
👍

**Comment by amazoradi** [comment]
🐖

**Pull request merged**
