### PR TITLE
Az search products

### LINKED ISSUE #4: User can search products to buy
**Given** the user is authenticated
**When** the user clicks on the search input field in the navigation bar
**And** the user types the name of a product
**When** pressed the enter key
**Then** products matching the keyword show in the page

### PR DESCRIPTION
**Pull request by amazoradi**
## Link to Ticket
Closes #4 (#4)

## Description of Proposed Changes
Adds a search field to navbar that searches product title and description, as shows all matches/partial matches. 

```sh
git fetch --all
git checkout az-searchProducts

```

## Impacted Areas in Application

List general components of the application that this PR will affect:
nav.html
urls.py
product_views.py

### CODE REVIEW

**Comment by braddavistech** [comment]
👍  Looks good! It looks like you may have a merge conflict from when I merged the ratings.

**Comment by Nolan-Little** [comment]
👍

**Comment by pragmatic-zac** [comment]
👍

**Comment by pragmatic-zac** [comment]
👎

**Pull request merged**
